[tool.poetry]
name = "aiofiles"
version = "22.1.0.dev0"
description = "File support for asyncio."
authors = ["Tin Tvrtkovic <tinchester@gmail.com>"]
license = "Apache-2.0"
readme = "README.rst"
repository = "https://github.com/Tinche/aiofiles"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-asyncio = "^0.15.1"
coverage = "^5.5"
tox = "^3.23.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
